# Generated by Django 3.0 on 2019-12-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.PositiveIntegerField()),
                ('GroupID', models.PositiveSmallIntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Grade', models.PositiveIntegerField()),
            ],
        ),
    ]
