# Generated by Django 3.0.2 on 2020-01-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['CourseID']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='Grade',
        ),
        migrations.AddField(
            model_name='course',
            name='Professor',
            field=models.ManyToManyField(to='Professor.Professor'),
        ),
    ]
