# Generated by Django 3.0.2 on 2020-01-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20200106_2036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('CourseID', 'GroupID')},
        ),
    ]
