# Generated by Django 2.0.7 on 2020-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('Course', '0003_auto_20200106_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Student',
            field=models.ManyToManyField(to='Student.Student'),
        ),
    ]
