# Generated by Django 2.0.7 on 2020-01-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('Course', '0005_remove_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Student',
            field=models.ManyToManyField(to='Student.Student'),
        ),
    ]
